/**
 * GetLinks Backend Test
 * GetLinks backend test document
 *
 * OpenAPI spec version: 1.0.0
 * Contact: isman.usoh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from "./api";
export * from "./configuration";
