"use strict";
// tslint:disable
/**
 * GetLinks Backend Test
 * GetLinks backend test document
 *
 * OpenAPI spec version: 1.0.0
 * Contact: isman.usoh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./api"));
__export(require("./configuration"));
